apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PhamNgocTuan2000/K8s-version1.git
    targetRevision: HEAD
    path: https://github.com/PhamNgocTuan2000/K8s-version1/argocd-app  # Thay thế bằng đường dẫn đến ứng dụng của bạn trong repository
  destination:
    server: https://kubernetes.default.svc
    namespace: tuanpn  # Thay thế bằng namespace bạn muốn triển khai ứng dụng
  syncPolicy:
    automated:
      prune: true
