apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
        - name: argocd
          image: argoproj/argocd:v2.6.1
          ports:
            - containerPort: 8080
          command:
            - argocd
            - argocd-server
          args:
            - --insecure
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-service
spec:
  selector:
    app: argocd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: http://argocd-service:8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-role-binding
subjects:
  - kind: ServiceAccount
    name: argocd-sa
    namespace: default
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
